# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: MrFriz Discgolf Rennes
email: discgolf@mrfriz.fr
description: > # this means to ignore newlines until "baseurl:"
  MrFriz a ouvert une section disc golf lors de l'ag clotuirant la saison 2015-2016
baseurl: "/discgolf" # the subpath of your site, e.g. /blog
lang: "fr"
url: "http://www.mrfriz.fr" # the base hostname & protocol for your site
twitter_username:
github_username:  mrfriz
disqus_username:

# Build settings
markdown: kramdown
relative_permalinks: false
permalink: /:categories/:title/

# Posts settings
future: true
safe: false
lsi: false
excerpt_separator: "\n\n"

default_bg: 'rainbow.jpg'

collections:
  parcours:
    output: true

compress_html:
  comments: ["<!-- ", " -->"]
  clippings: all
  endings: all


sass:
  sass_dir: assets/_sass


images: '/assets/images'
